# Disables color.
# Conflicts with: color, separator_color
no_color = false 

# Hides the separator.
# Conflicts with: separator_color
no_separator = false 

# Hides bar delimiters
no_bar_delimiter = true 

# Hides the title of the box surrounding system information
# Conflicts with: box_title
no_title = true 

# Disables the box surrounding system information.
# Conflicts with: box_title
no_box = false 

# Disables ASCII art
no_ascii = false 

# Displays a palette of your active colorscheme
palette = false 

# Turns data into bars for specific readouts 
bar = true

# Prefer small ASCII variant.
# Conflicts with: no_ascii
small_ascii = false 

# Randomizes the color of the keys each time your run the program 
random_color = false

# Randomizes the color of the separator each time your run the program 
random_sep_color = false

# Specify a color for the keys.
# Conflicts with: no_color
# Accepted values (case-sensitive):
#   - White
#   - Black
#   - Blue
#   - Cyan
#   - Green
#   - Yellow
#   - Red
#   - Magenta
color = "Yellow"

# Specify a color for the separator.
# Conflicts with: no_color
# Accepted values (case-sensitive):
#   - White
#   - Black
#   - Blue
#   - Cyan
#   - Green
#   - Yellow
#   - Red
#   - Magenta
separator_color = "Green"

# Shorten uptime format
short_uptime = true 

# Lengthen shell output
long_shell = false 

# Specify the title of the box
# Conflicts with: no_title.
# box_title = " Archemis "

# Specify the horizontal inner margin value of the box surrounding system information.
# Conflicts with: no_box
box_inner_margin_x = 2

# Specify the vertical inner margin value of the box surrounding system information.
# Conflicts with: no_box
box_inner_margin_y = 0

# Specify the theme to use
# Accepted values (case-insensitive):
#   - Hydrogen
#   - Helium
#   - Lithium
#   - Beryllium
#   - Boron
#
# Custom themes are also supported, they should be placed
# in $XDG_DATA_HOME/macchina/themes and must be a JSON file.
# 
# To set 'foobar' as a theme, place foobar.json 
# in $XDG_DATA_HOME/macchina/themes
# and set theme = "foobar" (case-sensitive)
theme = "archemis"

# Displays only the specified readouts.
# Conflicts with: hide 
# Accepted values (case-sensitive):
#   - Host
#   - Machine 
#   - Kernel
#   - Distribution
#   - OperatingSystem
#   - DesktopEnvironment
#   - WindowManager
#   - Packages
#   - LocalIP
#   - Terminal
#   - Shell
#   - Uptime
#   - Processor
#   - ProcessorUsage
#   - Memory
#   - Battery
# Example:
#   show_only = ["Battery", "Memory", ...]
show_only = ["Kernel", "WindowManager", "Shell", "Uptime", "ProcessorUsage", "Memory", "Battery"]
